language: node_js
node_js:
  - '6'
  - 'node'
script: npm run build
jobs:
  include:
    - stage: npm release
      if: branch = master AND tag IS present
      node_js: '6'
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true